name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore StoreApp/
    - name: Build
      run: dotnet build StoreApp/ --configuration Release --no-restore
    - name: Test
      run: dotnet test StoreApp/ --no-restore --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: dotnet publish Store App/ --configuration Release -o ./publish
      - name: deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: storeAppSatyam # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: ./publish
